### ISSUE TITLE
Movie or shows not shown

### ISSUE THREAD

**Issue by TopperBG** [lingarr-translate/lingarr#33]
docker-compose.yml
```
services:
  lingarr:
    image: lingarr/lingarr:latest
    container_name: lingarr
    restart: unless-stopped
    ports:
      - "9876:8080"
    volumes:
      - /home/lib/Movies:/media/Movies #match with radarr
      - /home/lib/tv:/media/tv #match with sonarr
      - /root/docker/etc/lingarr:/app/config
    networks:
      - lingarr
  LibreTranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,bg # Important, replace with your preferred languages
    ports:
      - 5000:5000
    volumes:
      - /root/docker/etc/libretranslate:/home/libretranslate/.local/share/argos-translate
    networks:
      - lingarr
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
networks:
  lingarr:
    external: true

```
log:

```
lingarr           | [2024-11-25 10:47:15] [Information] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
lingarr           | [2024-11-25 10:47:15] [Information] Microsoft.Hosting.Lifetime: Hosting environment: Production
lingarr           | [2024-11-25 10:47:15] [Information] Microsoft.Hosting.Lifetime: Content root path: /app
lingarr           | [2024-11-25 10:47:27] [Information] Lingarr.Server.Listener.SettingChangedListener: Settings changed for Radarr. All settings are complete, indexing media...
lingarr           | [2024-11-25 10:47:30] [Information] Lingarr.Server.Listener.SettingChangedListener: Settings changed for Sonarr. All settings are complete, indexing media...
lingarr           | [2024-11-25 10:47:44] [Information] Lingarr.Server.Jobs.GetMovieJob: Radarr job initiated
lingarr           | [2024-11-25 10:47:44] [Information] Lingarr.Server.Jobs.GetMovieJob: Fetched 202 movies from Radarr
lingarr           | [2024-11-25 10:47:45] [Information] Lingarr.Server.Jobs.GetMovieJob: Movies processed successfully.
lingarr           | [2024-11-25 10:47:45] [Information] Lingarr.Server.Jobs.GetShowJob: Sonarr job initiated
lingarr           | [2024-11-25 10:47:45] [Information] Lingarr.Server.Jobs.GetShowJob: Fetched 5 shows from Sonarr
lingarr           | [2024-11-25 10:47:46] [Information] Lingarr.Server.Jobs.GetShowJob: Processed and saved 5 out of 5 shows
lingarr           | [2024-11-25 10:47:46] [Information] Lingarr.Server.Jobs.GetShowJob: Shows processed successfully.
lingarr           | [2024-11-25 10:48:09] [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN8D7Q6TMOU6", Request id "0HN8D7Q6TMOU6:00000002": An unhandled exception was thrown by the application.
lingarr           | System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/lib/Movies/Fantasy Island (2020)'.
lingarr           |    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
lingarr           |    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
```

But even API connection to Radarr/Sonarr is ok and movies/shows are fetched - almost nothing is shown. 

![image](https://github.com/user-attachments/assets/5cdb20ba-3c8a-422c-bd24-0ce46a8913df)
![image](https://github.com/user-attachments/assets/fe24e3a4-a323-4cb6-aa3f-2161c58099e4)

Am I missing something in config?
That test stack works ok (radarr/sonarr/plex/tautuli/kometa/overseerr etc)
