### ISSUE TITLE
Unable to view subtitles

### ISSUE THREAD

**Issue by masterbalby2** [lingarr-translate/lingarr#36]
### Describe the problem

Hello everyone,
here is my problem.
I installed lingarr with the following compose.yml :
>services:
  lingarr:
    image: lingarr/lingarr:latest
    container_name: lingarr
    restart: unless-stopped
    ports:
      - "9876:8080"
    volumes:
      - /movies/:/movies #match with radarr
      - /tv/:/tv #match with sonarr
      - ./config:/app/config
  LibreTranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,fr  # Important, replace with your preferred languages
    ports:
      - 5000:5000
    volumes:
      - /root/config_libretranslate:/home/libretranslate/.local/share/argos-translate
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]`

I can see my different TV shows with the different seasons and episodes, but I can't see any of the subtitles.
They do exist and are in .srt format, but I can't see them.
Any idea why?

### Screenshots or Additional Context

![Capture d'écran 2024-12-09 082558](https://github.com/user-attachments/assets/4d6a95dc-2600-4123-8eb3-71c35edbab40)

**Comment by rowanfuchs** [comment]
Hi, the issue is caused due to an incorrect volume configuration, could you share your Sonarr and Radarr volume configuration and the root folder configuration within the media management setting.

**Comment by masterbalby2** [comment]
Here is the requested information:

In sonarr the mount directory for my series is `/mnt/FREEBOX_Videos/SERIES`

In the lingarr compose : 
`/mnt/FREEBOX_Videos/SERIES/:/tv`

I haven't touched the settings / mapping section in lingarr

**Comment by rowanfuchs** [comment]
How does that look in your sonarr docker compose? like this `/mnt/FREEBOX_Videos/SERIES:/mnt/FREEBOX_Videos/SERIES` or like this `/mnt/FREEBOX_Videos/SERIES:tv`

**Comment by masterbalby2** [comment]
I don't use docker for my sonarr instance.
it's a traditional installation.
My videos are mounted on` /mnt/FREEBOX_Videos` using fstab

**Comment by rowanfuchs** [comment]
I'm not sure if I understand, but the solution lays in matching the mount path with that from sonarr, if that is `/mnt/FREEBOX_Videos/SERIES` you will have to add a configuration within Lingarr as following: `/mnt/FREEBOX_Videos/SERIES/:/mnt/FREEBOX_Videos/SERIES/`

**Comment by masterbalby2** [comment]
I've just started all over again.

I switched to a sonarr under docker with the following setup:
`/tv:/tv`

Then for lingarr I also put the following mount:
`/tv/:/tv/`
In Integrations, I entered the sonarr address `http://192.168.0.91:8989` and its `API key`

Finally, I clicked on Sync libraries

In TV Shows I can see my series and episodes, but I still can't see the subtitle files.

I'm going crazy...

**Comment by rowanfuchs** [comment]
I've asked a few questions to help triage this issue, but I haven't received answers to them yet. It's a bit challenging to assist without all the necessary information. Based on what I can gather, the issue seems to be related to a mismatch in the volume configuration with Sonarr. The reason you can see the shows is that the sync is done via the API, but the subtitles are retrieved through a folder lookup.

I need:
Volume configuration of Sonarr
Root Folder configuration of Sonarr (under media management)
As you changed path's, I need to know what path is under a series

**Comment by masterbalby2** [comment]
Volume configuration of Sonarr `/tv:/tv`
Root Folder configuration of sonarr `/tv`
for 9-1-1, for example, here's the path `/tv/9-1-1`

**Comment by rowanfuchs** [comment]
alright, if you try the `dev` tag you should see which path's arrive in Lingar's import via the console. There is a chance that Sonarr now only output's `9-1-1` and not `/tv/9-1-1`. Try the following compose and keep an eye on the console when syncing libraries via the settings:


```
services:
  lingarr:
    image: lingarr/lingarr:dev
    container_name: lingarr-prod
    ports:
      - "9876:8080"
    environment:
    volumes:
      - /tv:/tv
```

**Comment by alansari** [comment]
Its possible that the issue the OP is facing is not sorting the tv series into season folders?

**Comment by rowanfuchs** [comment]
> ossible that the issue the OP is facing is not sorting the tv series into season folders?

Good observation, thank you @alansari ! that could definitely be the case.
@masterbalby2 in addition to the above test docker-compose, what folder structure does the shows `9-1-1` have?

**Comment by masterbalby2** [comment]
I'm back.
I've started all over again.
For my tests, I chose two TV shows: `9-1-1` and` Chicago Med`.
For `9-1-1`, the files are stored in the` /tv/9-1-1/` directory.
For `Chicago Med` the files are in `/tv/Chicago_med/Season1`.
The only subtitle files displayed are those located in a season subdirectory, i.e. those for `Chicago Med`.
I therefore confirm that the subtitles must be located in a season subdirectory.

Now I can see the subtitles but lingarr doesn't detect the language. Lingarr displays `UNKNOWN` even though they are in `English`.
How can I fix this?

**Comment by masterbalby2** [comment]
![Capture d'écran 2024-12-13 140924](https://github.com/user-attachments/assets/2be42b9b-715b-4351-95ca-85f9bd70d968)

**Comment by rowanfuchs** [comment]
Great finds, it's indeed an issue if the folder structure doesn't contain seasons. I've been investigating if this can be improved. This doesn't affect automated translation, so you don't have to change the structure if you use that.

As for language recognition, Lingarr currently only supports  ISO 639-2, or 639-3 codes which are `en`, or `eng` for example depending on the translation service as they also only have a offering of a few supported languages.

Out of curiosity, what kind of setup are you looking for? manual or automated? how do you end up watching your series. I am planning more features to cover more use cases, I might be able to make it easier in the future.

**Comment by masterbalby2** [comment]
If I download the subtitles manually, I get the `UNKNOWN` flag.
However, if I use bazarr to download them, I get the `EN` flag.
I can then translate them into the desired language (French).
So I've got a fully functional lingarr instance.
Cool

**Comment by masterbalby2** [comment]
2nd point:
I'm going to use lingarr to translate only a few subtitles for series that aren't yet available in my language, despite their fairly long release dates.
To watch the series, I use Kodi on an NViDIA Shield. A SAMBA mount is used between my NVIDIA Shield and the Synology that hosts the video files.
Thanks for your help and patience

**Comment by rowanfuchs** [comment]
Sadly such a feature isn't planned, Bazarr is great and works great with providing subtitles. Lingarr is meant as an additive.

**Comment by addreeh** [comment]
Hi, I think that I am getting the same error, this is my compose:

```
sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /hdd/jellyfin/tvshows:/tv/hdd
      - /hdd1tb/jellyfin/tvshows:/tv/hdd1tb
      - /hdd1tb/jellyfin/downloads:/downloads
      - /home/adripino/.arr/config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      arr_network:
        ipv4_address: 172.26.1.4
        
lingarr:
    image: lingarr/lingarr:latest
    container_name: lingarr
    restart: unless-stopped
    ports:
      - 9876:8080
    volumes:
      - /hdd1tb/jellyfin/tvshows:/tv/hdd1tb
      - /home/adripino/.arr/config/lingarr:/app/config
    networks:
        arr_network:
          ipv4_address: 172.26.1.14
  LibreTranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=es,en  # Important, replace with your preferred languages
      - PUID=1000
      - PGID=1000
    ports:
      - 5000:5000
    volumes:
      - /home/adripino/.arr/config/libretranslate:/home/libretranslate/.local/share/argos-translate
    networks:
        arr_network:
          ipv4_address: 172.26.1.15
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
```
      
it recognizes the series and episodes, but dont show any subtitle:
![{1BF8CAB9-FBDA-4A1E-BD2C-222F3BA68A2C}](https://github.com/user-attachments/assets/ae160ccc-e523-491e-995f-79fe48774222)
